# Generated by Django 2.2.2 on 2019-06-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('ingredients', models.ManyToManyField(to='recipes2.Ingredient')),
            ],
        ),
    ]
